# Generated by Django 5.2.5 on 2025-08-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_manage_users', 'Peut gérer les utilisateurs'), ('can_manage_recruitment', 'Peut gérer le recrutement'), ('can_apply_jobs', 'Peut postuler aux offres')]},
        ),
    ]
