# Generated by Django 5.2.5 on 2025-08-28 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('competences_requises', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['actif', 'date_creation'], name='recruitment_actif_67ceac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('lettre_motivation_file', models.FileField(blank=True, null=True, upload_to='lettres/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('submitted', 'Soumise'), ('in_review', 'En revue'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='submitted', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recruitment.poste')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_ia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommandation_ia', models.TextField(blank=True)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='recruitment.candidature')),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['statut', 'date_soumission'], name='recruitment_statut_f954ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('candidat', 'poste'), name='unique_candidature_par_poste'),
        ),
    ]
