# Generated by Django 5.2.5 on 2025-08-28 16:15

import recruitment.utils
import recruitment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=recruitment.utils.upload_to_cv, validators=[recruitment.validators.DocumentUploadValidator()]),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation_file',
            field=models.FileField(blank=True, null=True, upload_to=recruitment.utils.upload_to_lettre, validators=[recruitment.validators.DocumentUploadValidator()]),
        ),
    ]