# Generated by Django 5.2.5 on 2025-08-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidature",
            name="statut",
            field=models.CharField(
                choices=[
                    ("submitted", "Soumise"),
                    ("in_review", "En revue"),
                    ("interview", "Entretien"),
                    ("accepted", "Acceptée"),
                    ("rejected", "Refusée"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
