# Generated by Django 5.2.5 on 2025-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_alter_candidature_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="poste",
            name="type_contrat",
            field=models.CharField(
                choices=[("CDI", "CDI"), ("CDD", "CDD"), ("Alternance", "Alternance")],
                default="CDI",
                max_length=20,
            ),
        ),
    ]
